services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    restart: always
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=test
