name: Build and Test Next.js App
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Upload .next build folder
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser: [chrome]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Download .next build folder
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next

      - name: Install dependencies
        run: npm ci

      - name: Run tests on ${{ matrix.browser }}
        run: npx start-server-and-test start http://localhost:3000 "cypress run --browser ${{ matrix.browser }} --e2e"

      - name: Upload test videos as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-videos-${{ matrix.browser }}
          path: cypress/videos
          retention-days: 5

      - name: Upload test failure screenshots as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 5
